name: build-ics

on:
  schedule:
    - cron: "0 18 * * *"   # 03:00 JST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Ensure docs dir exists
        run: mkdir -p docs

      - name: Generate ICS (best-effort)
        run: |
          python scripts/run_all.py || true

      - name: Debug tree
        run: |
          ls -la
          echo "---- docs ----"
          ls -la docs || true

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/*.ics || true
          git commit -m "update ics" || echo "no changes"
          git push
